// generated by Fast Light User Interface Designer (fluid) version 1.0301

#ifndef GUITEST_h
#define GUITEST_h
#include <FL/Fl.H>
void MENU_CB(Fl_Widget*, void* Data);
void WIN_QUIT_CB(Fl_Widget*, void*);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
extern Fl_Button *Go_Button;
extern Fl_Button *Import_Button;
extern Fl_Button *Export_Button;
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Counter.H>
#include <FL/Fl_Spinner.H>
#include <FL/Fl_Scrollbar.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Value_Output.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Progress.H>
extern Fl_Menu_Item menu_[];
#define Menu_Save (menu_+1)
#define Menu_Import (menu_+2)
#define Menu_Export (menu_+3)
#define Menu_Go (menu_+4)
#define Menu_Project (menu_+7)
#define Menu_Team (menu_+8)
#define Menu_HowToUse (menu_+11)
#endif
